<a href="https://colab.research.google.com/github/ujwal23/SQL-Injection-Detection-using-ML-Approaches/blob/main/sql_injection_detection_using_ml_approaches.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
import pandas as pd
import numpy as np
import glob
import time
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import tree
# import tensorflow as tf
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D
import tensorflow as tf
tf.__version__

!sudo pip3 install keras

from tensorflow.python.keras.engine.sequential import Sequential

from tensorflow.python.keras.layers import Dense, Conv2D, Flatten, Dropout, MaxPooling2D
import pickle
from sklearn.metrics import accuracy_score
from keras.models import load_model

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(name=fn, length=len(uploaded[fn])))

Saving sqli.csv to sqli (1).csv
User uploaded file "sqli (1).csv" with length 723152 bytes


In [ ]:
df = pd.read_csv('/content/sqli.csv',encoding='utf-16')

In [ ]:
df.head()

Sentence  Label
0                a      1
1              a'       1
2            a' --      1
3  a' or 1 = 1; --      1
4                @      1

vectorization

In [ ]:
vector = CountVectorizer( max_df=0.7, max_features=4096, stop_words=stopwords.words('english'))
new_sent = vector.fit_transform(df['Sentence'].values.astype('U')).toarray()

In [ ]:
#Printing the identified Unique words along with their indices
print("Sentences: ", vector.vocabulary_)

Sentences:  {'union': 3829, 'userid': 3866, 'null': 2491, 'email': 1248, 'anything': 309, 'select': 3271, 'count': 966, 'tabname': 3633, 'members': 2308, 'full_name': 1501, 'like': 2126, 'bob': 537, '23': 55, 'exec': 1320, 'master': 2265, 'xp_cmdshell': 4061, 'ping': 2695, '172': 26, '10': 4, '255': 59, 'user_name': 3865, 'dbo': 1053, 'desc': 1103, 'users': 3868, 'username': 3867, 'lower': 2191, 'substring': 3573, 'top': 3729, 'name': 2436, 'sysobjects': 3625, 'xtype': 4063, '116': 17, 'uni': 3828, 'utl_http': 3875, 'request': 3039, 'http': 1740, 'admin': 184, 'utl_inaddr': 3876, 'get_host_address': 1534, 'banner': 448, 'version': 3908, 'rownum': 3144, 'sys': 3624, 'login_user': 2163, 'dual': 1194, 'instance': 1858, 'distinct': 1157, 'all_users': 240, 'password': 2631, 'user': 3863, 'table_name': 3629, 'all_tables': 239, 'column_name': 799, 'all_tab_columns': 238, 'granted_role': 1571, 'dba_role_privs': 1052, 'grantee': 1572, 'limit': 2129, 'loginuser': 2164, 'bin': 511, '15': 22, 'hex

In [ ]:
len(vector.vocabulary_.keys())

4096

In [ ]:
print(new_sent)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 2]]


In [ ]:
new_sent.shape=(4200,64,64,1)
new_sent.shape

(4200, 64, 64, 1)

In [ ]:
X=new_sent
y=df['Label']

In [ ]:
print(X)

[[[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 ...


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]

In [ ]:
# spliting training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
trainX=X_train.copy()
trainX.shape=(X_train.shape[0],trainX.shape[1]*trainX.shape[2])
testX=X_test.copy()
testX.shape=(testX.shape[0],testX.shape[1]*testX.shape[2])


naive bayes

In [ ]:
nb = GaussianNB()
nb.fit(trainX, y_train)
pred_nb = nb.predict(testX)

svm
support vector machine

In [ ]:
clf = SVC(gamma='auto')
clf.fit(trainX, y_train)
pred_svm=clf.predict(testX)

logistic regression

In [ ]:
clff = LogisticRegression(random_state=0).fit(trainX, y_train)
pred_lr=clff.predict(testX)

knn classifier

In [ ]:
kn = KNeighborsClassifier(n_neighbors=3)
kn.fit(trainX, y_train)
pred_knn = kn.predict(testX)

decision tree


In [ ]:
dt = tree.DecisionTreeClassifier()
dt = dt.fit(trainX, y_train)
pred_dt = dt.predict(testX)

neural network


In [ ]:
from tensorflow import keras
model = keras.Sequential()

model.add(keras.layers.Conv2D(64, (3, 3), activation='relu', input_shape=(64, 64, 1)))
model.add(keras.layers.MaxPooling2D((2, 2)))

model.add(keras.layers.Conv2D(128, (3, 3), activation='relu'))
model.add(keras.layers.MaxPooling2D((2, 2)))

model.add(Flatten())
model.add(Dense(64,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 62, 62, 64)        640       
                                                                 
 max_pooling2d (MaxPooling2  (None, 31, 31, 64)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 29, 29, 128)       73856     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 14, 14, 128)       0         
 g2D)                                                            
                                                                 
 module_wrapper (ModuleWrap  (None, 25088)             0         
 per)                                                            
                                                        

In [ ]:
classifier_nn = model.fit(X_train,y_train,epochs=10,validation_data=(X_test, y_test),batch_size=32)

Epoch 1/10
105/105 [==============================] - 66s 606ms/step - loss: 0.1633 - accuracy: 0.9312 - val_loss: 0.1122 - val_accuracy: 0.9524
Epoch 2/10
105/105 [==============================] - 62s 589ms/step - loss: 0.0889 - accuracy: 0.9643 - val_loss: 0.1018 - val_accuracy: 0.9524
Epoch 3/10
105/105 [==============================] - 65s 625ms/step - loss: 0.0725 - accuracy: 0.9688 - val_loss: 0.0914 - val_accuracy: 0.9655
Epoch 4/10
105/105 [==============================] - 52s 494ms/step - loss: 0.0596 - accuracy: 0.9732 - val_loss: 0.0983 - val_accuracy: 0.9631
Epoch 5/10
105/105 [==============================] - 45s 428ms/step - loss: 0.0559 - accuracy: 0.9750 - val_loss: 0.0985 - val_accuracy: 0.9655
Epoch 6/10
105/105 [==============================] - 46s 436ms/step - loss: 0.0545 - accuracy: 0.9747 - val_loss: 0.1033 - val_accuracy: 0.9667
Epoch 7/10
105/105 [==============================] - 44s 423ms/step - loss: 0.0532 - accuracy: 0.9780 - val_loss: 0.0978 - val_ac

In [ ]:
 pred=model.predict(X_test)

27/27 [==============================] - 3s 103ms/step


In [ ]:
for i in range(len(pred)):
    if pred[i]>0.5:
        pred[i]=1
    elif pred[i]<=0.5:
        pred[i]=0

In [ ]:
def accuracy_function(tp,tn,fp,fn):
  accuracy = (tp+tn) / (tp+tn+fp+fn)
  return accuracy

In [ ]:
def precision_function(tp,fp):
  precision = tp / (tp+fp)
  return precision

In [ ]:
def recall_function(tp,fn):
  recall=tp / (tp+fn)
  return recall

In [ ]:
def confusion_matrix(truth,predicted):

    true_positive = 0
    true_negative = 0
    false_positive = 0
    false_negative = 0

    for true,pred in zip(truth,predicted):

        if true == 1:
            if pred == true:
                true_positive += 1
            elif pred != true:
                false_negative += 1

        elif true == 0:
            if pred == true:
                true_negative += 1
            elif pred != true:
                false_positive += 1

    accuracy=accuracy_function(true_positive, true_negative, false_positive, false_negative)
    precision=precision_function(true_positive, false_positive)
    recall=recall_function(true_positive, false_negative)

    return (accuracy,
            precision,
           recall)

In [ ]:
accuracy,precision,recall=confusion_matrix(y_test,pred)

In [ ]:
print(" For CNN \n Accuracy : {0} \n Precision : {1} \n Recall : {2}".format(accuracy, precision, recall))

 For CNN 
 Accuracy : 0.9714285714285714 
 Precision : 0.916058394160584 
 Recall : 0.996031746031746


In [ ]:
accuracy,precision,recall=confusion_matrix(y_test,pred_nb)
print(" For Naive Bayes Accuracy : {0} \n Precision : {1} \n Recall : {2}".format(accuracy, precision, recall))

 For Naive Bayes Accuracy : 0.9773809523809524 
 Precision : 0.9298892988929889 
 Recall : 1.0


In [ ]:

accuracy,precision,recall=confusion_matrix(y_test,pred_svm)
print(" For SVM Accuracy : {0} \n Precision : {1} \n Recall : {2}".format(accuracy, precision, recall))

 For SVM Accuracy : 0.7642857142857142 
 Precision : 1.0 
 Recall : 0.21428571428571427


In [ ]:
accuracy,precision,recall=confusion_matrix(y_test,pred_knn)
print(" For KNN Accuracy : {0} \n Precision : {1} \n Recall : {2}".format(accuracy, precision, recall))


 For KNN Accuracy : 0.5833333333333334 
 Precision : 0.4186046511627907 
 Recall : 1.0


In [ ]:
accuracy,precision,recall=confusion_matrix(y_test,pred_lr)
print(" For Logistic Regression Accuracy : {0} \n Precision : {1} \n Recall : {2}".format(accuracy, precision, recall))

 For Logistic Regression Accuracy : 0.9285714285714286 
 Precision : 0.9848484848484849 
 Recall : 0.7738095238095238


In [ ]:
accuracy,precision,recall=confusion_matrix(y_test,pred_dt)
print(" For Decision Tree Accuracy : {0} \n Precision : {1} \n Recall : {2}".format(accuracy, precision, recall))

 For Decision Tree Accuracy : 0.8869047619047619 
 Precision : 0.7262247838616714 
 Recall : 1.0
